[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.45"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1.environment]
HUGO_VERSION = "0.45"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.68.3"

[context.branch-deploy.environment]
HUGO_VERSION = "0.68.3"
